class QALocators:
    QA_PAGE_TITLE = "//h1[contains(text(), 'Quality Assurance')]"
    JOBS_BUTTON = "//a[contains(text(), 'See all QA jobs')]"
    JOBS_PAGE_LANG_DROPDOWN = "//a[@id='lang-dropdown']"
    LOCATION_FILTER_DROPDOWN = "filter-by-location"
    DEPARTMENT_FILTER_DROPDOWN = "filter-by-department"
    JOBS_LIST = "//div[@id='jobs-list']"
    LISTED_QA_JOB = "//div[@data-location='istanbul-turkiye' and @data-team='qualityassurance']"
    NO_JOBS_AVAILABLE = "//p[contains(text(),'No positions available.')]"
    DEPARTMENT_FILTER = "//label[contains(text(),'Filter by Department')]/..//span[contains(text(),'Quality Assurance')]"
    LISTED_JOB_ITEM = "//div[@id='jobs-list']/..//div[contains(@class, 'position-list-item-wrapper')]"
    LISTED_JOB_ITEM_POSITION = "//p[contains(text(),'Quality Assurance')]"
    LISTED_JOB_ITEM_DEPARTMENT = "//span[contains(text(), 'Quality Assurance')]"
    LISTED_JOB_ITEM_LOCATION = "//div[contains(text(), 'Istanbul, Turkiye')]"
    BROWSE_OPEN_POSITIONS = "//h3[contains(.,'Open Positions')]"
    LISTED_JOB_ITEM_VIEW_ROLE_BUTTON = "//a[contains(text(), 'View Role')]"
